apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/ramamannava/Flux
  secretRef:
    name: example-app-2-github